################################################################################

default_config:

################################################################################

zeroconf:

################################################################################
#abilita la modalità yaml
lovelace:
  mode: yaml

################################################################################
#abilita i temi
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: auto
  
###############################   DEFAULT   ####################################

homeassistant:
#abilita l'uso dei pachetti
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config
  customize: !include customize.yaml
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: Europe/Rome
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
  name: Casa
recorder:
  #purge_interval: 1
  purge_keep_days: 3
  commit_interval: 60
  include:
    domains:
    - sensor
    - climate
    - binary_sensor
  exclude:
    entities:
    - sensor.last_boot
    - sensor.date
    - sensor.time
    - sensor.workday
    - sun.sun

###############################   HTTP   #######################################

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5
  
      
################################   IFTTT & REST  #####################################

ifttt:
  key: !secret ifttt_key
  
rest_command:
  mount_hd:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/mountHD'
  umount_hd:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/umountHD'
  reboot_server:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/reboot'
  poweroff_server:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/poweroff'
  mount_wd:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/mount_wd'
  umount_wd:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/umount_wd'
  mount_wd2:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/mount_wd2'
  umount_wd2:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/umount_wd2'
  mount_w3:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/mount_wd3'
  umount_w3:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/umount_wd3'
  mount_toshiba:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/mount_toshiba'
  umount_toshiba:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/umount_toshiba'
  mount_hitachi:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/mount_hitachi'
  umount_hitachi:
    url: 'http://192.168.1.xxx:xxxx/hassio/nas/umount_hitachi'
#########################   TELEGRAM   #########################################
#configura bot di telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id
#definisce i servizi di notifica tramite telegram e tramite alexa
notify:
  - name: notifiche
    platform: telegram
    chat_id: !secret telegram_chat_id
  - platform: alexa_media
    name: alexa_media
      
################################################################################

automation old: !include_dir_merge_list automations
script : !include_dir_merge_named scripts
group: !include groups.yaml

#############################   ENTITIES   #####################################

climate: !include /config/entities/climate.yaml
input_boolean: !include /config/entities/input_boolean.yaml
input_number: !include /config/entities/input_number.yaml
sensor: !include /config/entities/sensor.yaml
switch: !include /config/entities/switch.yaml
timer: !include /config/entities/timer.yaml
yeelight: !include /config/entities/yeelight.yaml
#############################   SHELL   ########################################

#########################   DISCOVERY   ########################################

discovery:
  ignore:
    - yeelight
    - igd
    - xiaomi_gw

shelly:
  upgrade_switch: false
  discovery: true
  show_id_in_name: false
  devices:
    - id: "xxxxx"
      light_switch: true
      name: Luce bagno
    - id: "xxxxx"
      light_switch: true
      name: Luce scale
    - id: "xxxxx"
      light_switch: true
      name: Luce camera
api:
alexa: !include /config/entities/alexa.yaml

    
