################################################################################

default_config:

################################################################################

zeroconf:

################################################################################

lovelace:
  mode: yaml
####################################################
#                                                  #
#                  RESOURCES                       #
#                                                  #
####################################################
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/gauge-card/gauge-card.js
      type: js
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity/battery-entity.js?v=0.2
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js?track=true
      type: js
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?v=0.3.2
      type: js
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: js
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module

####################################################
    - url: /hacsfiles/monster-card/monster-card.js
      type: js
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js?v=1
      type: module
    - url: /hacsfiles/popup-card/popup-card.js?track=true
      type: js
#lovelace: !include /config/lovelace.yaml 
################################################################################

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: auto
  
###############################   DEFAULT   ####################################

homeassistant:
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config
  customize: !include customize.yaml
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: Europe/Rome
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
  name: Casa
recorder:
  #purge_interval: 1
  purge_keep_days: 3
  commit_interval: 60
  include:
    domains:
    - sensor
    - climate
    - binary_sensor
  exclude:
    entities:
    - sensor.last_boot
    - sensor.date
    - sensor.time
    - sensor.workday
    - sun.sun

###############################   HTTP   #######################################

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: False
  login_attempts_threshold: 5
  
      
################################   IFTTT & REST  #####################################

ifttt:
  key: !secret ifttt_key
  
rest_command:
  reboot_retropie:
    url: 'http://192.168.1.118:1234/rest/reboot'
  poweroff_retropie:
    url: 'http://192.168.1.118:1234/rest/poweroff'
  mount_hd:
    url: 'http://192.168.1.14:1234/hassio/nas/mountHD'
  umount_hd:
    url: 'http://192.168.1.14:1234/hassio/nas/umountHD'
  reboot_server:
    url: 'http://192.168.1.14:1234/hassio/nas/reboot'
  poweroff_server:
    url: 'http://192.168.1.14:1234/hassio/nas/poweroff'
  mount_wd:
    url: 'http://192.168.1.14:1234/hassio/nas/mount_wd'
  umount_wd:
    url: 'http://192.168.1.14:1234/hassio/nas/umount_wd'
  mount_wd2:
    url: 'http://192.168.1.14:1234/hassio/nas/mount_wd2'
  umount_wd2:
    url: 'http://192.168.1.14:1234/hassio/nas/umount_wd2'
  mount_w3:
    url: 'http://192.168.1.14:1234/hassio/nas/mount_wd3'
  umount_w3:
    url: 'http://192.168.1.14:1234/hassio/nas/umount_wd3'
  mount_toshiba:
    url: 'http://192.168.1.14:1234/hassio/nas/mount_toshiba'
  umount_toshiba:
    url: 'http://192.168.1.14:1234/hassio/nas/umount_toshiba'
  mount_hitachi:
    url: 'http://192.168.1.14:1234/hassio/nas/mount_hitachi'
  umount_hitachi:
    url: 'http://192.168.1.14:1234/hassio/nas/umount_hitachi'
#########################   TELEGRAM   #########################################

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id_u
notify:
  - name: notifiche_u
    platform: telegram
    chat_id: !secret telegram_chat_id_u
  - platform: alexa_media
    name: alexa_media
      
################################################################################

automation old: !include_dir_merge_list automations
script : !include_dir_merge_named scripts
group: !include groups.yaml

#############################   ENTITIES   #####################################

climate: !include /config/entities/climate.yaml
input_boolean: !include /config/entities/input_boolean.yaml
input_number: !include /config/entities/input_number.yaml
sensor: !include /config/entities/sensor.yaml
switch: !include /config/entities/switch.yaml
timer: !include /config/entities/timer.yaml
yeelight: !include /config/entities/yeelight.yaml

input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'
    
media_player:
  - platform: androidtv
    name: Fire TV Stick
    device_class: firetv
    host: 192.168.1.116
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    
#############################   SHELL   ########################################

shell_command:

#########################   DISCOVERY   ########################################

discovery:
  ignore:
    - yeelight
    - xiaomi_gw

shelly:
  upgrade_switch: false
  discovery: true
  show_id_in_name: false
  devices:
    - id: "xxxxx"
      light_switch: true
      name: Luce bagno
    - id: "xxxxx"
      light_switch: true
      name: Luce scale
    - id: "xxxxx"
      light_switch: true
      name: Luce camera
    # - id: "xxxxx"
    #   name: Switch termostato
api:
alexa: !include /config/entities/alexa.yaml
