############################   ACCENDI LUCE CAMERA   ###########################
- alias: accendi_luce_camera_flip_90
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x00158d00027de0c8
  condition:
    - condition: template
      value_template: '{{ ''flip90'' == trigger.payload_json.action }}'
  action:
    - service: light.toggle
      data:
        entity_id: light.shelly_shsw_1_xxxxx  #luce camera
- alias: accendi_luce_camera_button
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x000b57fffe9f2b3c
  condition:
    - condition: template
      value_template: '{{ ''toggle'' == trigger.payload_json.action }}'
  action:
    - service: light.toggle
      data:
        entity_id: light.shelly_shsw_1_xxxxx  #luce camera
- alias: accendi_luce_camera_long_press
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x00158d00032699e9
  condition:
    - condition: template
      value_template: '{{ ''long_release'' == trigger.payload_json.click }}'
  action:
    - service: light.toggle
      data:
        entity_id: light.shelly_shsw_1_xxxxx  #luce camera

- alias: accendi_scale_e_poi_camera
  trigger:
    - platform: state
      entity_id: light.shelly_shsw_1_xxxxx  #luce scale
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '23:00:00'
    - condition: state
      entity_id: light.shelly_shsw_1_xxxxx  #luce camera
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_shsw_1_xxxxx  #luce camera
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: light.shelly_shsw_1_xxxxx  #luce scale
        
- alias: spegni_bagno_e_poi_accendi_comodino
  trigger:
    - platform: state
      entity_id: light.shelly_shsw_1_xxxxx  #luce bagno
      from: 'on'
      to: 'off'
  condition:
    - condition: time
      before: '06:00:00'
      after: '23:00:00'
    - condition: state
      entity_id: light.shelly_shsw_1_xxxxx  #luce camera
      state: 'on'
  action:
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: light.shelly_shsw_1_xxxxx  #luce camera
    - service: light.turn_on
      data:
        entity_id: light.comodino
