# - alias: pippo
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x00158d00027de0c8
#   condition:
#     - condition: template
#       value_template: '{{ ''rotate_right'' == trigger.payload_json.action }}'
#   action:
#     - service_template: >
#         {% if is_state('light.comodino', 'on') %}
#           script.increase_brightness
#         {% else %}
#           script.turn_on_to_increase
#         {% endif %}
# - alias: pippo2
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x00158d00027de0c8
#   condition:
#     - condition: template
#       value_template: '{{ ''rotate_left'' == trigger.payload_json.action }}'
#   action:
#     - service_template: >
#         {% if is_state('light.comodino', 'on') %}
#           script.decrease_brightness
#         {% else %}
#           script.turn_on_to_decrease
#         {% endif %}
# - alias: pippo3
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x000b57fffe9f2b3c
#   condition:
#     - condition: template
#       value_template: '{{ ''toggle'' == trigger.payload_json.action }}'
#   action:
#     - service: light.toggle
#       data:
#         entity_id: light.comodino
# - alias: pippo4
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x000b57fffe9f2b3c
#   condition:
#     - condition: template
#       value_template: '{{ ''brightness_up_click'' == trigger.payload_json.action }}'
#     - condition: state
#       entity_id: light.comodino
#       state: 'on'
#   action:
#     - service: light.turn_on
#       data_template:
#         entity_id: light.comodino
#         brightness: '{{states.light.comodino.attributes.brightness + 30}}'
# - alias: pippo5
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x000b57fffe9f2b3c
#   condition:
#     - condition: template
#       value_template: '{{ ''brightness_down_click'' == trigger.payload_json.action }}'
#     - condition: state
#       entity_id: light.comodino
#       state: 'on'
#   action:
#     - service: light.turn_on
#       data_template:
#         entity_id: light.comodino
#         brightness: '{{states.light.comodino.attributes.brightness - 30}}'
# - alias: pippo6
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x000b57fffe9f2b3c
#   condition:
#     - condition: template
#       value_template: '{{ ''arrow_right_click'' == trigger.payload_json.action }}'
#     - condition: state
#       entity_id: light.comodino
#       state: 'on'
#   action:
#     - service: light.turn_on
#       data_template:
#         entity_id: light.comodino
#         color_temp: '{{states.light.comodino.attributes.color_temp + 50}}'
# - alias: pippo7
#   trigger:
#     - platform: mqtt
#       topic: zigbee2mqtt/0x000b57fffe9f2b3c
#   condition:
#     - condition: template
#       value_template: '{{ ''arrow_left_click'' == trigger.payload_json.action }}'
#     - condition: state
#       entity_id: light.comodino
#       state: 'on'
#   action:
#     - service: light.turn_on
#       data_template:
#         entity_id: light.comodino
#         color_temp: '{{states.light.comodino.attributes.color_temp - 50}}'
############################   ACCENDI LUCE CAMERA   ###########################
- alias: accendi_luce_camera_flip_90
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x00158d00027de0c8
  condition:
    - condition: template
      value_template: '{{ ''flip90'' == trigger.payload_json.action }}'
  action:
    - service: light.toggle
      data:
        entity_id: light.shelly_shsw_1_55dfe4  #luce camera
- alias: accendi_luce_camera_button
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x000b57fffe9f2b3c
  condition:
    - condition: template
      value_template: '{{ ''toggle'' == trigger.payload_json.action }}'
  action:
    - service: light.toggle
      data:
        entity_id: light.shelly_shsw_1_55dfe4  #luce camera
- alias: accendi_luce_camera_long_press
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/0x00158d00032699e9
  condition:
    - condition: template
      value_template: '{{ ''long_release'' == trigger.payload_json.click }}'
  action:
    - service: light.toggle
      data:
        entity_id: light.shelly_shsw_1_55dfe4  #luce camera

- alias: accendi_scale_e_poi_camera
  trigger:
    - platform: state
      entity_id: light.shelly_shsw_1_76f7d1  #luce scale
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      before: '06:00:00'
      after: '23:00:00'
    - condition: state
      entity_id: light.shelly_shsw_1_55dfe4  #luce camera
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_shsw_1_55dfe4  #luce camera
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: light.shelly_shsw_1_76f7d1  #luce scale
        
- alias: spegni_bagno_e_poi_accendi_comodino
  trigger:
    - platform: state
      entity_id: light.shelly_shsw_1_7703e4  #luce bagno
      from: 'on'
      to: 'off'
  condition:
    - condition: time
      before: '06:00:00'
      after: '23:00:00'
    - condition: state
      entity_id: light.shelly_shsw_1_55dfe4  #luce camera
      state: 'on'
  action:
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: light.shelly_shsw_1_55dfe4  #luce camera
    - service: light.turn_on
      data:
        entity_id: light.comodino